name: "Test on Latest Laravel"

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: PHPUnit Hand Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Composer update
        run: composer self-update >/dev/null 2>&1

      - name: Lock laravel/framework version
        env:
          LARAVEL_VERSION: 12.69.3
        run: composer require laravel/framework:12.69.3 --no-update -W

      - name: Vendor update
        run: composer update --prefer-source --no-interaction

      - name: Run test suites
        run: composer run-script test

      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls -v
