name: PHP8.3

# Manual run
on: workflow_dispatch

jobs:
  matrix-build:
    name: PHPUnit Tests Matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Composer update
        run: composer self-update >/dev/null 2>&1

      - name: Lock laravel/framework version
        env:
          LARAVEL_VERSION: 11.57
        run: composer require laravel/framework:11.57 --no-update -W

      - name: Vendor update
        run: composer update --prefer-source --no-interaction

      - name: Run test suites
        run: composer run-script test

      # - name: Analyze
      #   run: vendor/bin/phpstan analyse -c phpstan.neon ./src/

      # - name: phpcs
      #   run: php vendor/bin/phpcs --standard=PSR12 ./src/
