name: PHP tests

# Run on push, PR and manually
on: 
  push:
    branches:
      - stable
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  matrix-build:
    name: PHPUnit Tests Matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [8.2, 8.3]
        laravel-version:
          [
            "9.*", # Test latest version
            "10.*", # Test latest version
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer update
        run: composer self-update >/dev/null 2>&1

      - name: Lock laravel/framework version
        env:
          LARAVEL_VERSION: ${{ matrix.laravel-version }}
        run: composer require laravel/framework:${{ matrix.laravel-version }} --no-update

      - name: Vendor update
        run:
          composer config minimum-stability dev &&
          composer update --prefer-stable --prefer-dist --no-progress

      - name: Run test suites
        run: composer run-script test

      # - name: Analyze
      #   run: vendor/bin/phpstan analyse -c phpstan.neon ./src/

      # - name: phpcs
      #   run: php vendor/bin/phpcs --standard=PSR12 ./src/
